// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using AtrinGol.Finance.Model.Finances;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace AtrinGol.Finance.Models.Finances;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFinanceAppService), typeof(FinanceClientProxy))]
public partial class FinanceClientProxy : ClientProxyBase<IFinanceAppService>, IFinanceAppService
{
    public virtual async Task<FinanceDto> CreateAsync(CreateUpdateFinanceDto input)
    {
        return await RequestAsync<FinanceDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateUpdateFinanceDto), input }
        });
    }

    public virtual async Task<FinanceDto> UpdateAsync(long id, CreateUpdateFinanceDto input)
    {
        return await RequestAsync<FinanceDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id },
            { typeof(CreateUpdateFinanceDto), input }
        });
    }

    public virtual async Task DeleteAsync(long id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<FinanceDto> GetAsync(long id)
    {
        return await RequestAsync<FinanceDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(long), id }
        });
    }

    public virtual async Task<PagedResultDto<FinanceDto>> GetListAsync(PagedResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<FinanceDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedResultRequestDto), input }
        });
    }
}
