// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using AtrinGol.Contract.Models.Contracts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace AtrinGol.Contract.Models.Contracts;

public interface IContractAppService : IApplicationService
{
    Task<ContractDto> GetAsync(long id);

    Task<PagedResultDto<ContractDto>> GetListAsync(PagedResultRequestDto input);

    Task<ContractDto> CreateAsync(CreateUpdateContractDto input);

    Task<ContractDto> UpdateAsync(long id, CreateUpdateContractDto input);

    Task DeleteAsync(long id);
}
