// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using AtrinGol.Finance.Samples;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace AtrinGol.Finance.Samples;

public class SampleDto
{
    public int Value { get; set; }
}
